name: Bug Report
description: Report a bug with clear acceptance criteria for when it’s resolved
title: "[BUG]: "
labels: [bug]
body:
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Short title describing the bug
      placeholder: e.g. Login button does not redirect
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug, including steps to reproduce if possible.
      placeholder: Explain what’s broken, how to reproduce, and expected vs. actual behavior.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Provide a **numbered list** of conditions that define when the bug is fixed.
      placeholder: |
        - [ ] Login button redirects correctly to the dashboard
        - [ ] User session is created successfully
        - [ ] No console errors appear during login
    validations:
      required: true
