name: Bug Issue
description: Report a bug with clear acceptance criteria for when it’s resolved
title: "[BUG]: "
labels: [bug]
body:
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Short title describing the bug
      placeholder: e.g. GET endpoint returns 404
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug, including steps to reproduce if possible.
      placeholder: Explain what’s broken, how to reproduce, and expected vs. actual behavior.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Provide a **checklist** of conditions that define when the bug is fixed.
      placeholder: |
        - [ ] GET request to endpoint returns 200 OK status code
        - [ ] Response includes expected data in the correct format
        - [ ] Error logs show no exceptions or failures
    validations:
      required: true
