name: Feature Request
description: Suggest a new feature with clear acceptance criteria
title: "[Feature]: "
labels: [enhancement]
body:
  - type: input
    id: title
    attributes:
      label: Feature Title
      description: Short title for this feature
      placeholder: e.g. Add dark mode toggle
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen.
      placeholder: Explain the feature in detail...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Provide a **numbered list** of conditions that must be met.
      placeholder: |
        1. User can enable/disable dark mode
        2. Setting is persisted after reload
        3. Works across all pages
    validations:
      required: true
