name: Verify

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.CONFORM }}

  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          java-version: "24"
          distribution: "corretto"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Checkstyle
        run: mvn --batch-mode clean verify checkstyle:check

  pmd:
    runs-on: ubuntu-latest
    name: PMD

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: "24"
          distribution: "corretto"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run PMD Analysis
        run: mvn --batch-mode clean pmd:check

  cyclonedx:
    runs-on: ubuntu-latest
    name: SBOM
    permissions:
      contents: read
      security-events: write
    strategy:
      max-parallel: 4
      matrix:
        java-version: [ "24" ]
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1 (optional: for pipeline security, as in original)
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "temurin"  # Or "corretto"; Temurin is widely used for recent Java versions

      - name: Generate SBOM with CycloneDX
        run: mvn cyclonedx:makeAggregateBom  # Use 'cyclonedx:makeBom' for single-module; outputs to target/bom.json (configurable)

      - uses: anchore/scan-action@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8 # v7 (optional: for vulnerability scanning)
        id: anchore
        with:
          sbom: target/bom.json  # Adjust if using XML or custom output
          fail-build: false  # Informational; set to true to fail on issues
          severity-cutoff: medium

      - uses: github/codeql-action/upload-sarif@64d10c13136e1c5bce3e5fbde8d4906eeaafc885 # v3 (optional: upload scan results)
        with:
          sarif_file: ${{ steps.anchore.outputs.sarif }}
        continue-on-error: true  # Handles potential invalid SARIF

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: sbom
          path: target/bom.*


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 24
          cache: maven

      - name: Run Tests
        run: mvn -B test

  build:
    runs-on: ubuntu-latest
    needs:
      - test
      - checkstyle
      - pmd
      - cyclonedx
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 24
          cache: maven

      - name: Clean and Compile
        run: mvn -B clean compile